spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost/mydatabase
    username: postgres
    password: postgres

liquibase:
  changeLogFile: src/main/resources/db/changelog/db.changelog-master.yaml

logging:
  configuration:
    status: warn
    appenders:
      - name: Console
        type: Console
        target: SYSTEM_OUT
        PatternLayout:
          pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    loggers:
      - name: root
        level: info
        appender-ref:
          - ref: Console

openapi:
  info:
      title: Spring-Boot-Base-API
      description: A base on which to develop an API using Spring
      version: 1.0.0
